### ISSUE TITLE
"Segment has already been emitted" when streaming

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-xray-sdk-java#69]
SDK version: 2.2.1
Java version: 1.8.0_202

We've run into the known issue of [large traces not sending correctly over UDP](https://github.com/aws/aws-xray-sdk-java/issues/4) so had enabled streaming with the `DefaultStreamingStrategy`, and configured it to stream in chunks of 10. However, we see a large number of errors in the logs like this:

```
com.amazonaws.xray.exceptions.AlreadyEmittedException: Segment foo has already been emitted.
```

It looks like `DefaultStreamingStrategy` is careful to [lock and unlock](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/DefaultStreamingStrategy.java#L73) access to the list of subsegments in a trace, to avoid synchronization issues. However, this lock is *not* checked (as far as I can see) when the whole trace is finished - meaning it's possible that X-Ray attempts to stream the same segments twice.

**Comment by Neonage** [comment]
+1
Same here with same SDK version.
The issue is on an asynch task in java.
I try to set the trace entity but i got AlreadyEmittedException.

**Comment by awssandra** [comment]
Hi ashleymercer,

Thanks for the code dive, and sorry for the trouble. We'll take a look into this and post back when we have an update.

**Comment by luluzhao** [comment]
@ashleymercer @Neonage Could you guys tell me more about your use cases? Does your application deal with multi-threading(i.e open another thread and try to add subsegment into the segment and then streaming)?

**Comment by Neonage** [comment]
@luluzhao yes, in my use case, i tried to open a new asynch task but the sdk send a segment before completing the second thread. Maybe we need a mechanism to lock the "send segment function" before having all the asynch tasks completed.
Another solution could be to send subsegments with the reference to a segment already sent.

**Comment by ashleymercer** [comment]
@luluzhao yes my code is also multi-threaded. In my case, I think (but need to do more investigation) that I have:

- one background thread which finishes some trace segment: if this segment tips the trace over the threshold set in `DefaultStreamingStrategy` it starts to stream part of the trace

- the main thread (in parallel) returns and finishes the trace at the top level; this then causes the main recorder to send the whole trace back to X-Ray

If these aren't properly synchronised, it's possible for them to clash giving rise to the "Segment already emitted" errors. I could do this synchronisation externally (in my code) but it would make my code a lot simpler if I could rely on the X-Ray library to do this for me.

**Comment by IvyDev0** [comment]
Same here. Any updates?

**Comment by chanchiem** [comment]
We are in the process of getting this reproduced so that we can get a solution out. If anyone has any reproduction code, it would immensely help in this effort. It looks like we might need some extra lock checking mechanisms.

The weird thing is that during the locking period, the stream method takes care to remove the subsegment from the actual entity [here](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/DefaultStreamingStrategy.java#L107), so if the whole trace is finished, and it attempts to send the segment, any streamed subsegment would already be removed--since it all happens during the locking period. I'll investigate further and report anything I can find.

**Comment by matt1hathcock** [comment]
any updates on this bug?

**Comment by anuraaga** [comment]
Hi @matt1hathcock - thanks for checking reminding us of this issue. I believe this may have been fixed as part of #182 - did you happen to see the error recently? If so let us know what version you're on so we can double check. Thanks a lot!

**Comment by matt1hathcock** [comment]
> Hi @matt1hathcock - thanks for checking reminding us of this issue. I believe this may have been fixed as part of #182 - did you happen to see the error recently? If so let us know what version you're on so we can double check. Thanks a lot!

We are using 2.7.1 aws xray.... The error is the same as that mentioned in earlier posts com.amazonaws.xray.exceptions.AlreadyEmittedException: Segment foo has already been emitted. We are passing the trace id into async methods and have for the meantime removed xrayenabled on the async methods to avoid logging the segment emitted errors.

**Comment by willarmiros** [comment]
Sorry to hear this issue is still happening @matt1hathcock. Could you try setting your `CONTEXT_MISSING_STRATEGY` to the default `RUNTIME_ERROR` option and post the stacktrace of this exception? It looks like we don't actually know exactly where this is happening, just guess work, so a stacktrace would be nice. 

We throw an `AlreadyEmittedException` for any modification of a (sub)segment including streaming them, so could you also share some repro code or at least which X-Ray APIs (`putAnnotation`, `addException`, etc) you're using?

**Comment by matt1hathcock** [comment]
No problem @willarmiros ended up getting a work around defining the executors.

**Comment by matt1hathcock** [comment]
> Great to hear @matt1hathcock! Did you use our [SegmentContextExecutors](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/contexts/SegmentContextExecutors.java) or something else? It would be awesome if you could explain a little more in case other customers are hitting this.

@willarmiros this article should be helpfulf for a workaround http://www.chrisport.ch/java/2016/10/12/java-spring-context-aware.html
